# Generated by Django 2.2.7 on 2019-12-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0005_auto_20191222_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-course', 'day', 'time']},
        ),
    ]
