# Generated by Django 2.2.7 on 2019-12-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMap', '0006_auto_20191223_1731'),
        ('TimeTable', '0006_auto_20191223_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(51040, '5А'), (51041, '5Б'), (51042, '5В'), (51043, '5Г'), (61040, '6А'), (61041, '6Б'), (61042, '6В'), (61043, '6Г'), (71040, '7А'), (71041, '7Б'), (71042, '7В'), (71043, '7Г'), (81040, '8А'), (81041, '8Б'), (81042, '8В'), (81043, '8Г'), (91040, '9А'), (91041, '9Б'), (91042, '9В'), (91043, '9Г'), (101040, '10А'), (101041, '10Б'), (111040, '11А'), (111041, '11Б')], max_length=3, unique=True, verbose_name='Класс')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day', 'course', 'time']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='room',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=20, verbose_name='День'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Название')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchoolMap.Room', verbose_name='Кабинет')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TimeTable.Subject'),
            preserve_default=False,
        ),
    ]
