# Generated by Django 2.2.7 on 2019-12-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0008_auto_20191226_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.SmallIntegerField(choices=[(51040, '5А'), (51041, '5Б'), (51042, '5В'), (51043, '5Г'), (61040, '6А'), (61041, '6Б'), (61042, '6В'), (61043, '6Г'), (71040, '7А'), (71041, '7Б'), (71042, '7В'), (71043, '7Г'), (81040, '8А'), (81041, '8Б'), (81042, '8В'), (81043, '8Г'), (91040, '9А'), (91041, '9Б'), (91042, '9В'), (91043, '9Г'), (101040, '10А'), (101041, '10Б'), (111040, '11А'), (111041, '11Б')], unique=True, verbose_name='Класс'),
        ),
    ]
