# Generated by Django 2.2.7 on 2019-12-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0011_auto_20191227_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Предмет'),
        ),
    ]
