# Generated by Django 2.2.7 on 2020-01-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('title', models.CharField(default='О нас', max_length=20)),
            ],
        ),
    ]
