# Generated by Django 2.2.7 on 2019-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('introduce', models.TextField(default='')),
                ('number', models.CharField(max_length=3)),
                ('floor', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
