# Generated by Django 2.2.7 on 2019-12-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='introduce',
            field=models.TextField(blank=True, default=''),
        ),
    ]
