# Generated by Django 2.2.7 on 2019-12-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMap', '0003_auto_20191218_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=3),
        ),
    ]
